version: '3.3'

services:
  api:
    image: ghcr.io/osahft/osahft-api:1.0.0
    container_name: osahft-api
    volumes:
      - type: bind
        source: ./api.properties
        target: /etc/osahft/api.properties
    networks:
      - osahft
      - osahft_db
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy

    restart: on-failure

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: osahft-elasticsearch
    environment:
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    networks:
      - osahft_db
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:${ELASTICSEARCH_PASSWORD} -s http://localhost:9200/_cat/health?h=status | grep -q 'green\\|yellow'"]
      interval: 30s
      timeout: 10s


  kibana:
    image: kibana:7.14.2
    container_name: osahft-kibana
    networks:
      - osahft_db
    environment:
      - ELASTICSEARCH_URL=http://osahft-elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://osahft-elasticsearch:9200
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  app:
    image: ghcr.io/osahft/osahft-app:1.0.0
    container_name: osahft-app
    networks:
      - osahft
    ports:
      - "80:80"
    depends_on:
      - api

networks:
  osahft:
    driver: bridge
  osahft_db:
    driver: bridge