# This workflow uses several third-party actions to build a Docker image for the OSAHFT BACKEND (./api)
# and if the build succeeds, push the built image to GitHub Packages.

name: Create and publish docker image for osahft/api

on:
  push:
    branches:
      - "fix/workflows"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve version
        id: api-version
        working-directory: ./packages/api
        run: |
          echo "::set-output name=current-version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: $IMAGE_NAME to lowercase
          id: string
          uses: ASzc/change-string-case-action@v1
          with:
            string: ${{env.IMAGE_NAME}}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./packages/api
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:${{ steps.api-version.outputs.current-version }}
