# This workflow uses several third-party actions to build a Docker image for the OSAHFT FRONTEND (./app)
# and if the build succeeds, push the built image to GitHub Packages.

name: Create and publish Docker image for osahft/app

on:
  push:
    branches:
      - "develop"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-app

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        run: |
          cd packages/api
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          tags: |
#            type=semver,pattern={{version}},value=${{env.VERSION}}

      - name: Build and push APP Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./packages/app
          push: true
          tags: ${{env.VERSION}}
          labels: ${{ steps.meta.outputs.labels }}
