name: Build osahft and push docker images
'on':
  workflow_dispatch: null
  push:
    branches:
      - setup/combined-workflows
env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: '${{ github.repository }}-api'
  IMAGE_NAME_APP: '${{ github.repository }}-app'

jobs:
  buildApi:
    name: Build osahft-api and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pom version
        id: api-version
        working-directory: ./packages/api
        run: >
          echo "::set-output name=current-version::$(mvn help:evaluate
          -Dexpression=project.version -q -DforceStdout)"

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: '${{ env.REGISTRY }}'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: $IMAGE_NAME to lowercase
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: '${{env.IMAGE_NAME_API}}'

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./packages/api
          push: true
          tags: >-
            ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:${{
            steps.api-version.outputs.current-version }}

  buildApp:
    name: Build osahft-app and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./packages/app

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: '${{ env.REGISTRY }}'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: $IMAGE_NAME to lowercase
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: '${{env.IMAGE_NAME_APP}}'

      - name: Build and push APP Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./packages/app
          push: true
          tags: >-
            ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:${{
            steps.package-version.outputs.current-version}}-SNAPSHOT

  deployToServer:
    name: Trigger deployment to server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate timestamp for hook payload
        id: timestamp
        run: |
          echo "::set-output name=timestamp::${date +"%Y-%m-%d_%H-%M-%S}"

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: json-extended
          webhook_url: 'ec2-18-188-198-157.us-east-2.compute.amazonaws.com:9000/hooks/ghcr-deploy' # for testing interim aws instance
          webhook_secret: 'test123'
          #webhook_url: '${{ secrets.WEBHOOK_URL }}'
          #webhook_secret: '${{ secrets.WEBHOOK_SECRET }}'
          data: '{ "timestamp": "${{ steps.timestamp.outputs.timestamp }}" }'
