name: Trigger deployment to server

on:
  workflow_dispatch:
  push:
    branches:
      - setup/combined-workflows

jobs:
  deployToServer:
    name: Trigger deployment to server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate timestamp for hook payload
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(date +'%Y-%m-%d_%H-%M-%S')"

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: json-extended
          webhook_url: 'ec2-18-188-198-157.us-east-2.compute.amazonaws.com:9000/hooks/ghcr-deploy' # for testing interim aws instance
          webhook_secret: 'test123'
          #webhook_url: '${{ secrets.WEBHOOK_URL }}'
          #webhook_secret: '${{ secrets.WEBHOOK_SECRET }}'
          data: '{ "timestamp": "${{ steps.timestamp.outputs.timestamp }}" }'
